services:
  app-yolo-live:
    image: ghcr.io/amperecomputingai/ampere-ai-ref-apps:yolov8-0.3
    ipc: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      GRADIO_SERVER_NAME: ${GRADIO_SERVER_NAME:-0.0.0.0}
      GRADIO_SERVER_PORT: ${GRADIO_SERVER_PORT:-5000}
      HOST_PORT: ${HOST_PORT:-5000}
      INSTANCE_NAME: ${INSTANCE_NAME:-'AltraMax'}
      NSTREAMS: ${NSTREAMS:-4}
      NTHREADS: ${NTHREADS:-16}
      VIDEO_SRC: ${VIDEO_SRC:-''}
      WEBCAM0_SRC: ${WEBCAM0_SRC:-0}
      WEBCAM1_SRC: ${WEBCAM1_SRC:-2}
    ports:
      - "${HOST_PORT}:${GRADIO_SERVER_PORT:-5000}"
