services:
  app-whisper:
    #image: ghcr.io/amperecomputingai/ampere-ai-ref-apps:whisper-0.3
    image: ghcr.io/amperecomputingai/ampere-ai-ref-apps:whisper-0.3.1
    ipc: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      GRADIO_SERVER_NAME: ${GRADIO_SERVER_NAME:-0.0.0.0}
      GRADIO_SERVER_PORT: ${GRADIO_SERVER_PORT:-5001}
      HOST_PORT: ${HOST_PORT:-5001}
      INSTANCE_NAME: ${INSTANCE_NAME:-'AltraMax'}
      NSTREAMS: ${NSTREAMS:-1}
      NTHREADS: ${NTHREADS:-16}
    ports:
      - "${HOST_PORT}:${GRADIO_SERVER_PORT:-5001}"
